import 'product.dart';

class SampleData {
  static final List<String> categories = [
    'Vegetables',
    'Fruits',
    'Dairy & Eggs',
    'Meat & Poultry',
    'Herbs & Spices',
    'Baked Goods',
    'Preserves',
    'Honey & Syrup',
  ];

  static final List<Product> products = [
    Product(
      id: 'p1',
      name: 'Organic Tomatoes',
      description: 'Vine-ripened heirloom tomatoes grown without pesticides. Perfect for salads and sauces.',
      price: 4.99,
      unit: 'lb',
      category: 'Vegetables',
      imageUrl: 'https://images.unsplash.com/photo-1546470427-0d4db154ceb8?w=400',
      farmerId: 'f1',
      farmerName: 'Green Valley Farm',
      rating: 4.8,
      reviewCount: 124,
      isOrganic: true,
      stockQuantity: 50,
    ),
    Product(
      id: 'p2',
      name: 'Fresh Strawberries',
      description: 'Sweet, juicy strawberries picked at peak ripeness from our local fields.',
      price: 6.49,
      unit: 'pint',
      category: 'Fruits',
      imageUrl: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=400',
      farmerId: 'f1',
      farmerName: 'Green Valley Farm',
      rating: 4.9,
      reviewCount: 89,
      isOrganic: true,
      stockQuantity: 30,
    ),
    Product(
      id: 'p3',
      name: 'Farm Fresh Eggs',
      description: 'Free-range eggs from pasture-raised hens. Rich in flavor and nutrition.',
      price: 5.99,
      unit: 'dozen',
      category: 'Dairy & Eggs',
      imageUrl: 'https://images.unsplash.com/photo-1569288052389-dac9b01c9c05?w=400',
      farmerId: 'f2',
      farmerName: 'Sunrise Ranch',
      rating: 4.7,
      reviewCount: 203,
      stockQuantity: 40,
    ),
    Product(
      id: 'p4',
      name: 'Raw Honey',
      description: 'Pure, unfiltered wildflower honey from our local apiaries. Never heated or processed.',
      price: 12.99,
      unit: 'jar',
      category: 'Honey & Syrup',
      imageUrl: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=400',
      farmerId: 'f2',
      farmerName: 'Sunrise Ranch',
      rating: 4.9,
      reviewCount: 156,
      isOrganic: true,
      stockQuantity: 25,
    ),
    Product(
      id: 'p5',
      name: 'Baby Spinach',
      description: 'Tender baby spinach leaves, triple-washed and ready to eat. Great in salads and smoothies.',
      price: 3.99,
      unit: 'bag',
      category: 'Vegetables',
      imageUrl: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400',
      farmerId: 'f3',
      farmerName: 'Meadow Creek Farms',
      rating: 4.6,
      reviewCount: 67,
      isOrganic: true,
      stockQuantity: 45,
    ),
    Product(
      id: 'p6',
      name: 'Artisan Sourdough Bread',
      description: 'Handcrafted sourdough bread made with locally milled flour and a 100-year-old starter.',
      price: 7.49,
      unit: 'loaf',
      category: 'Baked Goods',
      imageUrl: 'https://images.unsplash.com/photo-1549931319-a545753467c8?w=400',
      farmerId: 'f3',
      farmerName: 'Meadow Creek Farms',
      rating: 4.8,
      reviewCount: 178,
      stockQuantity: 15,
    ),
    Product(
      id: 'p7',
      name: 'Grass-Fed Ground Beef',
      description: '100% grass-fed and grass-finished ground beef. No hormones or antibiotics.',
      price: 9.99,
      unit: 'lb',
      category: 'Meat & Poultry',
      imageUrl: 'https://images.unsplash.com/photo-1588347785102-5576c8a90b29?w=400',
      farmerId: 'f4',
      farmerName: 'Heritage Pastures',
      rating: 4.7,
      reviewCount: 92,
      stockQuantity: 35,
    ),
    Product(
      id: 'p8',
      name: 'Fresh Basil',
      description: 'Fragrant sweet basil grown in our greenhouse. Perfect for Italian dishes and pesto.',
      price: 2.49,
      unit: 'bunch',
      category: 'Herbs & Spices',
      imageUrl: 'https://images.unsplash.com/photo-1618164435735-413d3b066c9a?w=400',
      farmerId: 'f1',
      farmerName: 'Green Valley Farm',
      rating: 4.5,
      reviewCount: 45,
      isOrganic: true,
      stockQuantity: 60,
    ),
    Product(
      id: 'p9',
      name: 'Goat Cheese',
      description: 'Creamy chèvre made from the milk of our own herd. Mild and tangy.',
      price: 8.99,
      unit: 'log',
      category: 'Dairy & Eggs',
      imageUrl: 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=400',
      farmerId: 'f4',
      farmerName: 'Heritage Pastures',
      rating: 4.8,
      reviewCount: 71,
      stockQuantity: 20,
    ),
    Product(
      id: 'p10',
      name: 'Organic Blueberries',
      description: 'Hand-picked organic blueberries bursting with antioxidants and natural sweetness.',
      price: 5.99,
      unit: 'pint',
      category: 'Fruits',
      imageUrl: 'https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=400',
      farmerId: 'f2',
      farmerName: 'Sunrise Ranch',
      rating: 4.7,
      reviewCount: 98,
      isOrganic: true,
      stockQuantity: 25,
    ),
    Product(
      id: 'p11',
      name: 'Strawberry Jam',
      description: 'Small-batch strawberry preserves made with fresh berries and cane sugar.',
      price: 6.99,
      unit: 'jar',
      category: 'Preserves',
      imageUrl: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400',
      farmerId: 'f3',
      farmerName: 'Meadow Creek Farms',
      rating: 4.9,
      reviewCount: 134,
      stockQuantity: 30,
    ),
    Product(
      id: 'p12',
      name: 'Sweet Corn',
      description: 'Just-picked sweet corn, incredibly tender and sweet. Best eaten within days of harvest.',
      price: 1.49,
      unit: 'ear',
      category: 'Vegetables',
      imageUrl: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=400',
      farmerId: 'f1',
      farmerName: 'Green Valley Farm',
      rating: 4.6,
      reviewCount: 57,
      stockQuantity: 100,
    ),
  ];
}
